### ISSUE TITLE
同时支持API和AccessToken的访问

### ISSUE THREAD

**Issue by plutotree** [Chanzhaoyu/chatgpt-web#1058]
实现的效果如下

- 访问`https://xxx.com` 调用3.5的`API`版本`
- 访问`https://xxx.com/v4` 调用4.0的`AccessToken`版本

记录下，方便后续有需要的同学

## 使用docker-compose部署后端服务

修改`docker-compose.yml`（默认在`docker-compose`目录下，也可以挪到其他地方去），增加一个app服务，可以按照需求配置，这里一个使用API，一个使用ACCESS_TOKEN并指定为gpt-4

```yaml
services:
  app:
    image: chenzhaoyu94/chatgpt-web
    ports:
      - 3002:3002
    environment:
      OPENAI_API_KEY: "YOUR_API_KEY"
      OPENAI_ACCESS_TOKEN:
      OPENAI_API_BASE_URL:
      OPENAI_API_MODEL:
      API_REVERSE_PROXY:
      AUTH_SECRET_KEY:
      TIMEOUT_MS: 60000
      SOCKS_PROXY_HOST:
      SOCKS_PROXY_PORT:
      HTTPS_PROXY: 
  app2:
    image: chenzhaoyu94/chatgpt-web
    ports:
      - 3003:3002
    environment:
      OPENAI_API_KEY:
      OPENAI_ACCESS_TOKEN: "YOUR_ACCESS_TOKEN"
      OPENAI_API_BASE_URL:
      OPENAI_API_MODEL: gpt-4
      API_REVERSE_PROXY:
      AUTH_SECRET_KEY:
      TIMEOUT_MS: 60000
      SOCKS_PROXY_HOST:
      SOCKS_PROXY_PORT:
      HTTPS_PROXY: 
  nginx:
    image: nginx:alpine
    ports:
      - '13512:80'
    expose:
      - 'NGINX_PORT'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
      - app2
  ```

## 生成默认的前端目录

1. 在根目录下执行， `pnpm build`
2. 将生成后的`dist`目录下内容拷贝至`docker-compose/nginx/html`

## 生成v4版本的前端目录

1. 修改根目录下的`.env`文件，即将`/api`改为`/apiv4`，`3002`改为`3003`
    ```
    # Glob API URL
    VITE_GLOB_API_URL=/apiv4

    VITE_APP_API_BASE_URL=http://127.0.0.1:3003/
    ```
2. 在根目录下执行， `pnpm build`
3. 将生成后的`dist`目录下内容拷贝至`docker-compose/nginx/html/v4`.

## 修改docker-compose的nginx配置

1. 修改文件`docker-compose/nginx/nginx.conf`，主要是增加`/apiv4`的处理
    ```
       location /api {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_pass http://app:3002;
    }

    location /apiv4 {
        rewrite ^/apiv4(.*)$ /api$1 break;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_pass http://app2:3002;
    }
    ```

## 启动docker-compose

执行`docker-compose up -d`即可

## 修改本机转发相关配置

这里只要直接`proxy_pass`转发就可以了

以`nginx`为例

```
     location / { 
        proxy_pass http://127.0.0.1:13512;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
    }  
```
