### ISSUE TITLE
大家的反代还正常吗

### ISSUE THREAD

**Issue by zhaojie199512** [Chanzhaoyu/chatgpt-web#1465]
按照大佬的https://github.com/acheong08/ChatGPT-Proxy-V4自建了一个反代，之前一直正常使用，现在突然不行了，看日志是被cf拦截了，没有认证通过，有没有还能正常使用反代的小伙伴呀，用大佬的https://bypass.churchless.tech/api/conversation也不行，就很难受。

**Comment by zhaojie199512** [comment]
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func2 (3 handlers)
[GIN-debug] GET    /api/*path                --> main.proxy (3 handlers)
[GIN-debug] POST   /api/*path                --> main.proxy (3 handlers)
[GIN-debug] PUT    /api/*path                --> main.proxy (3 handlers)
[GIN-debug] PATCH  /api/*path                --> main.proxy (3 handlers)
[GIN-debug] HEAD   /api/*path                --> main.proxy (3 handlers)
[GIN-debug] OPTIONS /api/*path                --> main.proxy (3 handlers)
[GIN-debug] DELETE /api/*path                --> main.proxy (3 handlers)
[GIN-debug] CONNECT /api/*path                --> main.proxy (3 handlers)
[GIN-debug] TRACE  /api/*path                --> main.proxy (3 handlers)
[GIN-debug] POST   /admin/update             --> main.main.func3 (3 handlers)
2023/04/16 04:16:16 net.Listen error: listen tcp :8080: bind: address already in use
root@VM-0-10-ubuntu:/home/ChatGPT-Proxy-V4# ChatGPT-Proxy-V4 
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func2 (3 handlers)
[GIN-debug] GET    /api/*path                --> main.proxy (3 handlers)
[GIN-debug] POST   /api/*path                --> main.proxy (3 handlers)
[GIN-debug] PUT    /api/*path                --> main.proxy (3 handlers)
[GIN-debug] PATCH  /api/*path                --> main.proxy (3 handlers)
[GIN-debug] HEAD   /api/*path                --> main.proxy (3 handlers)
[GIN-debug] OPTIONS /api/*path                --> main.proxy (3 handlers)
[GIN-debug] DELETE /api/*path                --> main.proxy (3 handlers)
[GIN-debug] CONNECT /api/*path                --> main.proxy (3 handlers)
[GIN-debug] TRACE  /api/*path                --> main.proxy (3 handlers)
[GIN-debug] POST   /admin/update             --> main.main.func3 (3 handlers)
2023/04/16 04:16:34 97427 :8080
Got response: 403 Forbidden
Error: 403 Forbidden
<html>
  <head>
    <style global>body{font-family:Arial,Helvetica,sans-serif}.container{align-items:center;display:flex;flex-direction:column;gap:2rem;height:100%;justify-content:center;width:100%}@keyframes enlarge-appear{0%{opacity:0;transform:scale(75%) rotate(-90deg)}to{opacity:1;transform:scale(100%) rotate(0deg)}}.logo{color:#8e8ea0}.scale-appear{animation:enlarge-appear .4s ease-out}@media (min-width:768px){.scale-appear{height:48px;width:48px}}.data:empty{display:none}.data{border-radius:5px;color:#8e8ea0;max-width:420px;text-align:center;width:100%}.data ul{list-style:none;padding:0}@media (prefers-color-scheme:dark){body{background-color:#343541}.logo{color:#acacbe}}</style>
  </head>
  <body>
    <div class="container">
      <div class="logo">
        <svg
          width="41"
          height="41"
          viewBox="0 0 41 41"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          strokeWidth="2"
          class="scale-appear"
        >
          <path
            d="M37.5324 16.8707C37.9808 15.5241 38.1363 14.0974 37.9886 12.6859C37.8409 11.2744 37.3934 9.91076 36.676 8.68622C35.6126 6.83404 33.9882 5.3676 32.0373 4.4985C30.0864 3.62941 27.9098 3.40259 25.8215 3.85078C24.8796 2.7893 23.7219 1.94125 22.4257 1.36341C21.1295 0.785575 19.7249 0.491269 18.3058 0.500197C16.1708 0.495044 14.0893 1.16803 12.3614 2.42214C10.6335 3.67624 9.34853 5.44666 8.6917 7.47815C7.30085 7.76286 5.98686 8.3414 4.8377 9.17505C3.68854 10.0087 2.73073 11.0782 2.02839 12.312C0.956464 14.1591 0.498905 16.2988 0.721698 18.4228C0.944492 20.5467 1.83612 22.5449 3.268 24.1293C2.81966 25.4759 2.66413 26.9026 2.81182 28.3141C2.95951 29.7256 3.40701 31.0892 4.12437 32.3138C5.18791 34.1659 6.8123 35.6322 8.76321 36.5013C10.7141 37.3704 12.8907 37.5973 14.9789 37.1492C15.9208 38.2107 17.0786 39.0587 18.3747 39.6366C19.6709 40.2144 21.0755 40.5087 22.4946 40.4998C24.6307 40.5054 26.7133 39.8321 28.4418 38.5772C30.1704 37.3223 31.4556 35.5506 32.1119 33.5179C33.5027 33.2332 34.8167 32.6547 35.9659 31.821C37.115 30

**Comment by James-handsome** [comment]
[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later

**Comment by zynkchen** [comment]
一样情况

**Comment by zynkchen** [comment]
换另外一个反代可以用

**Comment by foamzou** [comment]
> 换另外一个反代可以用

有啥可用的反代，大伙分享下？cc @zynkchen

**Comment by pepperdog999** [comment]
同问，我试了一下社区常用的两个反代都不行了哦。

**Comment by LOG1997** [comment]
两个代理都挂了似乎

**Comment by wwlmm** [comment]
看来access token的方式 就要完蛋了

**Comment by bigSmartisan** [comment]
openai那边升级了验证方式，v1的反代炸了

**Comment by tianwen-j** [comment]
> openai那边升级了验证方式，v1的反代炸了

这可真是一个令人不愉快的消息

**Comment by LOG1997** [comment]
只能使用apikey的方式咯

**Comment by linweiyuan** [comment]
https://github.com/Chanzhaoyu/chatgpt-web/issues/1150

其实我做了个自建代理，开源的，虽然没有社区的稳定，但是今天也还能用，有兴趣的可以自己尝试一下，可以当作一个临时的解决方案，等他们修复了，再用他们的（没有特别蹭热度的意思）

如果服务器没有被封 IP：

```yaml
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web
    ports:
      - 3002:3002
    environment:
      OPENAI_API_KEY:
      OPENAI_ACCESS_TOKEN: accessToken
      OPENAI_API_BASE_URL:
      OPENAI_API_MODEL:
      API_REVERSE_PROXY: http:/go-chatgpt-api:8080/conversation
      AUTH_SECRET_KEY:
      MAX_REQUEST_PER_HOUR: 0
      TIMEOUT_MS: 60000
      SOCKS_PROXY_HOST:
      SOCKS_PROXY_PORT:
      HTTPS_PROXY:
    depends_on:
      - go-chatgpt-api

  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped
```

如果封了，也就是 `Access denied`：

```yaml
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web
    ports:
      - 3002:3002
    environment:
      OPENAI_API_KEY:
      OPENAI_ACCESS_TOKEN: accessToken
      OPENAI_API_BASE_URL:
      OPENAI_API_MODEL:
      API_REVERSE_PROXY: http:/go-chatgpt-api:8080/conversation
      AUTH_SECRET_KEY:
      MAX_REQUEST_PER_HOUR: 0
      TIMEOUT_MS: 60000
      SOCKS_PROXY_HOST:
      SOCKS_PROXY_PORT:
      HTTPS_PROXY:
    depends_on:
      - go-chatgpt-api

  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    restart: unless-stopped
```
