### ISSUE TITLE
我让gpt4总结了一下自建代理的搭建方法，在这里分享给需要的人

### ISSUE THREAD

**Issue by iknow2333** [Chanzhaoyu/chatgpt-web#1499]
参考https://blognas.hwb0307.com/linux/docker/4201

Model: GPT-4

> 1 / 1
> 
> 在VPS里自建反向代理 自建代理可能经常不可用。如果失败，等待一段时间（比如1小时）后再测试。 目前公共反向代理已经不太稳了。有能力的小伙伴建议自建反向代理，比如基于linweiyuan / go-chatgpt-api项目或linweiyuan/java-chatgpt-api项目。这些方法对VPS的IP纯净程度要求较高。自建反代的稳定性应该会比一些公共地址更稳定。 这里我们以linweiyuan / go-chatgpt-api为例，其实项目README也说得挺清楚了： work3=~/docker/go-chatgpt-api mkdir -p $work3; cd $work3 新建docker-compose.yml文件并填入以下内容： services: go-chatgpt-api: container\_name: go-chatgpt-api image: linweiyuan/go-chatgpt-api ports: - 8080:8080 # 宿主机8080端口可按需改为其它端口 environment: - GIN\_MODE=release - CHATGPT\_PROXY\_SERVER=http://chatgpt-proxy-server:9515 depends\_on: - chatgpt-proxy-server restart: unless-stopped chatgpt-proxy-server: container\_name: chatgpt-proxy-server image: linweiyuan/chatgpt-proxy-server restart: unless-stopped 完成部署后，必须要有这样的提示才算成功： chatgpt-proxy-server | ChromeDriver was started successfully. 这时，该自建IP的访问地址为http://<vps-ip>:8080/conversation，它可以作为下面的API\_REVERSE\_PROXY参数的值。请注意，如果该反代和你的chatgpt-web属于同一个docker网段，你也可以使用局域网地址： http://172.17.0.1:8080/conversation。具体原理为：docker在安装时会自动创建一个名为docker0的虚拟网络接口，并分配这个地址作为网桥的网关地址；而172.17.0.1 是docker的默认网桥地址。 如果显示Access denied之类的报错，提示IP被屏蔽。这时可以使用Cloudflare WARP。Cloudflare WARP是Cloudflare开发的VPN工具，它通过将用户的网络流量路由到Cloudflare的服务器上来保护用户的网络连接。WARP主要基于Cloudflare的全球边缘网络，其包含大量的服务器并分布在世界各地。当用户使用WARP连接到Cloudflare的VPN服务器时，其网络流量将会被路由到最接近目标网站的服务器上，从而可以绕过目标网站所设置的地理位置限制和IP封锁。此外，WARP还使用了一些高级的加密和安全措施来保护用户的数据和隐私。这些措施包括TLS 1.3加密、AES-256-GCM加密等。这些措施可以确保用户的网络连接和数据是安全的，并且不会被恶意方获取和利用。 我的RackNerd VPS就是基于WARP成功自建反向代理的： services: go-chatgpt-api: container\_name: go-chatgpt-api image: linweiyuan/go-chatgpt-api ports: - 8080:8080 # 宿主机8080端口可按需改为其它端口 environment: - GIN\_MODE=release - CHATGPT\_PROXY\_SERVER=http://chatgpt-proxy-server:9515 - NETWORK\_PROXY\_SERVER=socks5://chatgpt-proxy-server-warp:65535 depends\_on: - chatgpt-proxy-server - chatgpt-proxy-server-warp restart: unless-stopped chatgpt-proxy-server: container\_name: chatgpt-proxy-server image: linweiyuan/chatgpt-proxy-server restart: unless-stopped chatgpt-proxy-server-warp: container\_name: chatgpt-proxy-server-warp image: linweiyuan/chatgpt-proxy-server-warp restart: unless-stopped 这几个镜像体积还挺大的，总体积应该接近2G。所以玩docker的VPS真心推荐大容量的！ 总结在linux vps上安装此项目的方法

1 / 1

在 Linux VPS 上自建反向代理并安装 linweiyuan / go-chatgpt-api 项目的方法如下：

1.  安装 Docker 和 Docker Compose 确保你的 VPS 上已经安装了 Docker 和 Docker Compose。如果没有，请参考以下命令进行安装：

Docker 安装:

bash

```bash
curl -fsSL https://get.docker.com | sh
systemctl enable docker
systemctl start docker
```

Docker Compose 安装:

bash

```bash
curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

2.  创建工作目录

bash

```bash
work3=~/docker/go-chatgpt-api
mkdir -p $work3; cd $work3
```

3.  新建 docker-compose.yml 文件并填入以下内容：

yaml

```yaml
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080 # 宿主机8080端口可按需改为其它端口
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped
```

4.  部署项目 在含有 docker-compose.yml 文件的工作目录下，运行以下命令：

bash

```bash
docker-compose up -d
```

5.  确认部署成功 部署成功后，控制台应该出现如下提示：

`chatgpt-proxy-server  | ChromeDriver was started successfully.`

6.  使用自建反向代理 自建反向代理的访问地址为：`http://<vps-ip>:8080/conversation`，可作为 API\_REVERSE\_PROXY 参数的值。
    
7.  （可选）使用 Cloudflare WARP 如果出现 IP 被屏蔽的问题，可以考虑使用 Cloudflare WARP。在 docker-compose.yml 文件中添加相应的配置，然后重新部署。
    

总之，在 Linux VPS 上自建反向代理并安装 linweiyuan / go-chatgpt-api 项目的步骤如上所述。遵循这些步骤，你应该能够成功部署并使用自建反向代理。
