### ISSUE TITLE
自建代理的端口映射具体怎么配置

### ISSUE THREAD

**Issue by GitHubChrisChen8035** [Chanzhaoyu/chatgpt-web#1522]
chatgpt-web的yml配置里，
-ports:
 3002:3002

自建代理的yml配置里，
-ports:
 8080:8080

第一段我理解，搭建的web服务用vps.ip:3002端口访问，映射到容器的3002端口
第二段根据注释，冒号前面那个8080是宿主机端口，然后映射到容器8080端口

是不是得改成3002:8080？如果这样改，容器启动的时候会提示端口被占用。

改成以下这样，容器能正常run，但web访问不了
chatgpt-web的yml配置里，
-ports:
 3002:3012

自建代理的yml配置里，
-ports:
 3012:8080

看来对端口映射还是知之甚少。。

**Comment by huangwb8** [comment]
关于docker的端口映射，请看该文章：  [Docker系列 了解Docker Compose的配置文件](https://blognas.hwb0307.com/linux/docker/3880)

关于如何使用自建代理，请看该文章：  [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

有问题可以博客评论留言或在此issue继续提问。

**Comment by Usongkam** [comment]
自建代理不用映射到外面去，写在同一个yml里面直接用name访问8080端口就行。

**Comment by Timoshao** [comment]
我是用的docket部署的
自建代理的映射8080：8080
web-gpt端口映射：3002：3002   
代理配置：API_REVERSE_PROXY=http://代理ip:8080/conversation
命令如下成功了
docker run -d --name chatgpt-web  -p 3002:3002 -e OPENAI_API_MODEL=gpt-4 -e API_REVERSE_PROXY=http://代理ip:8080/conversation -e OPENAI_ACCESS_TOKEN=你的token chenzhaoyu94/chatgpt-web

**Comment by huangwb8** [comment]
@1205129045x  

一般都是有一个域名，然后通过域名解析ip，再通过nginx反向代理（通常是https）访问服务。  

具体可见： [Docker系列 两大神器NPM和ddns-go的安装](https://blognas.hwb0307.com/linux/docker/604)

**Comment by huangwb8** [comment]
@1205129045x 

这样看暂时看不出来。 你自己用`http://vps-ip:端口号`的方式访问试试看呗，成功就是正常运行了

**Comment by huangwb8** [comment]
@1205129045x 

chatgpt-web改成类似这样：

```
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web:latest
    ports:
      - 3002:3002 
    environment:
      OPENAI_ACCESS_TOKEN: 我的acesstoken
      API_REVERSE_PROXY: http://172.17.0.1:8080/conversation
```

当然，chatgpt-web的其它设置你也要做好。 这个我不太了解，因为我并不直接使用该项目。 我使用的是衍生项目 [Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web) 。

chatgpt-web和反向代理要在同一台VPS里，这样它们都处于一个名为`docker0`的内网中。

VPS的防火墙要开放8080和3002端口。 

这样，在本地电脑输入 `http://vpsip:3002` 就可以访问chatgpt的项目了。

你可以看我的教程了解更多细节： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
