### ISSUE TITLE
Error: ChatGPT error 429: {"detail":"It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy"}

### ISSUE THREAD

**Issue by KKK66661** [Chanzhaoyu/chatgpt-web#2006]

**Comment by watsmal** [comment]
https://watsmal.github.io/2024/01/05/linux/chatgpt/chatgpt_web%E6%90%AD%E5%BB%BA%E6%95%99%E7%A8%8B/ 可以参考这个博客，也可以给博主留言

**Comment by ReactLearningTrip** [comment]
报这个错误什么原因呀

**Comment by CongAn** [comment]
### 关键问题就是解决 `ChartGPT` 反向代理 不可用的问题，很明显 `PandoraNext` 现在就不可用。
使用 `docker compose` 搭建并启动自己的GPT反向代理服务器，其中 `socks5://1.1.1.1:1086` 需要修改为你自己实际的VPN翻墙代理服务地址。
```yml
# docker-compose.yml
version: '3.3'
services:
  ninja:
    hostname: ninja
    image: gngpp/ninja
    environment:
      - TZ=Asia/Shanghai
      - PROXIES=socks5://1.1.1.1:1086
    ports:
      - "7999:7999"
    restart: unless-stopped
    command: run
```

修改 `chatgpt-web/service/.env` 文件，其中 `2.2.2.2:7999` 需要修改为你自己实际的 `ninja` 服务的IP和端口。
```env
# Reverse Proxy - Available on accessToken
# Default: https://ai.fakeopen.com/api/conversation
# More: https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
API_REVERSE_PROXY=http://2.2.2.2:7999/backend-api/conversation
```
其他内容按照官网文档照常启动即可。

 参考了以下内容，希望修复下这个问题，或者文档里写明。
> https://github.com/Chanzhaoyu/chatgpt-web/issues/1973#issuecomment-1826716387
> https://hi.wyhhome.top/archives/qOK1fxka
