### ISSUE TITLE
If there's a way to add a custom API_KEY on the frontend?

### ISSUE THREAD

**Issue by ReiSuzunami** [Chanzhaoyu/chatgpt-web#246]
It is kinda inconvenient to change it through restarting the container

**Comment by pengmaochang** [comment]
you can use docker-compose deploy it. The backend has been build as a docker image uploaded into repository.
1. install a docker-compose app in your server
2. write a docker-compose.yml file in your folder ,code as follow:
```
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web
    ports:
      - 3002:3002
    environment:
      # choose one in follow two ways
      OPENAI_API_KEY: xxxx
      # choose one in follow two ways
      OPENAI_ACCESS_TOKEN: xxxxxx
      API_REVERSE_PROXY: xxx
      TIMEOUT_MS: 60000
      # work with SOCKS_PROXY_PORT
      SOCKS_PROXY_HOST: xxxx
      # work withSOCKS_PROXY_HOST
      SOCKS_PROXY_PORT: xxxx
```
3. run command to build and run the docker container of backend
```
docker-compose up -d
```
