### ISSUE TITLE
Docker compose yml 编写 有误吧

### ISSUE THREAD

**Issue by wxyShine** [Chanzhaoyu/chatgpt-web#48]
```yml
version: '3'
services:
  app:
    image: chenzhaoyu94/chatgpt-web
    ports:
      - 3002:3002
    environment:
      OPENAI_API_KEY: xxxxx
```

service: 改为 services:
