### ISSUE TITLE
为什么部署之后请不到数据

### ISSUE THREAD

**Issue by James-handsome** [Chanzhaoyu/chatgpt-web#493]
![微信图片_20230311142318](https://user-images.githubusercontent.com/54829185/224468825-f716da6c-3d71-4f96-b9e1-397e4c64a64e.png)
请求得不到数据啊

```
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY:  我的apikey
      # 二选一
      OPENAI_ACCESS_TOKEN: xxxxxx
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: xxxx
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL: xxxx
      # 反向代理，可选
      API_REVERSE_PROXY: xxx
      # 访问权限密钥，可选
      AUTH_SECRET_KEY: xxx
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST: xxxx
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT: xxxx
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

```
我只改了apikey那一项

nginx 配置如下
```
server {
	listen 80;
	server_name  localhost;
	charset utf-8;
	error_page   500 502 503 504  /50x.html;
	location / {
			root /usr/share/nginx/html;
   		try_files $uri /index.html;
	}

	location /api {
			proxy_set_header   X-Real-IP $remote_addr; #转发用户IP
			proxy_pass http://0.0.0.0:3002;   我改了这里
	}

	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header REMOTE-HOST $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

``` 

然后 启动了项目
docker-compose up -d
