### ISSUE TITLE
为什么我按照你的模式去部署的，但是直接访问 80 端口直接报错了啊

### ISSUE THREAD

**Issue by James-handsome** [Chanzhaoyu/chatgpt-web#507]
![image](https://user-images.githubusercontent.com/54829185/224481657-195e2a6c-69c5-4b3b-8abc-1bf1512c0ca4.png)

![image](https://user-images.githubusercontent.com/54829185/224481733-45060cbf-6302-40e8-95bf-ae5f606e5f83.png)

```
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY: sk-dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    
      OPENAI_API_MODEL: gpt-3.5-turbo
    
      AUTH_SECRET_KEY: 11111111
     
      TIMEOUT_MS: 60000
      
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app


```

这是我的配置项，难道哪里不对吗？
80端口访问不了项目
