### ISSUE TITLE
请求一个正确的示例配置，十分感谢

### ISSUE THREAD

**Issue by xiyuvi** [Chanzhaoyu/chatgpt-web#601]
我是这样写的，接口提示报错
```
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY: "sk-UV7asdasfewtfqdfwegwefedqfqwedqwedqweQKr2"
      # 二选一
      #OPENAI_ACCESS_TOKEN: xxxxxx
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      #OPENAI_API_BASE_URL: xxxx
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL: "text-davinci-002"
      # 反向代理，可选
      #API_REVERSE_PROXY: xxx
      # 访问权限密钥，可选
      AUTH_SECRET_KEY: "xiyu"
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      #SOCKS_PROXY_HOST: xxxx
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      #SOCKS_PROXY_PORT: xxxx
```
接口提示：
```
undefined
[ChatGPT error 404: {
"error": {
"message": "Invalid URL (POST /v1/chat/completions)",
"type": "invalid_request_error",
"param": null,
"code": null
}
}
]
```
好像是url无效的意思，是让我把可选参数没填的都设置成空字符串吗，还是必须给OPENAI_API_BASE_URL一个正确的值，感谢指导
