### ISSUE TITLE
docker搭建好了，但是有点问题

### ISSUE THREAD

**Issue by emmmua** [Chanzhaoyu/chatgpt-web#739]
前端页面可以访问，但是chatGPT回复就报错。
```json
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchSSE (/app/node_modules/.pnpm/chatgpt@5.0.10/node_modules/chatgpt/build/index.js:46:15) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8380:28)
      at node:internal/deps/undici/undici:8338:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8369:13)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```

**Comment by WadeZeak** [comment]
你的配置参数看看呢

**Comment by emmmua** [comment]
> 你的配置参数看看呢

# OpenAI API Key - https://platform.openai.com/overview
OPENAI_API_KEY=sk-NJwgE6****************68abwHY0QVw2bcUuEQa


# OpenAI API Base URL - https://api.openai.com
OPENAI_API_BASE_URL=https://openapi.ssiic.com

# Reverse Proxy
API_REVERSE_PROXY=https://bypass.duti.tech/api/conversation

# timeout
TIMEOUT_MS=100000

**Comment by emmmua** [comment]
> 你的配置参数看看呢

```
version: '3'

services:
  app:
    image: chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY: sk-NJw****************abwHY0QVw2bcUuEQa
      # 二选一
      # OPENAI_ACCESS_TOKEN: xxx
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: https://openapi.ssiic.com
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      # OPENAI_API_MODEL: xxx
      # 反向代理，可选
      API_REVERSE_PROXY: https://bypass.duti.tech/api/conversation
      # 访问权限密钥，可选
      # AUTH_SECRET_KEY: xxx
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 50
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      # SOCKS_PROXY_HOST: xxx
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      # SOCKS_PROXY_PORT: xxx
      # HTTPS_PROXY 代理，可选
      # HTTPS_PROXY: http://xxx:7890
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

```
