### ISSUE TITLE
chatgpt-web-app-1  | TimeoutError: OpenAI timed out waiting for response

### ISSUE THREAD

**Issue by tanpengsccd** [Chanzhaoyu/chatgpt-web#875]
```
chatgpt-web-app-1  | sendMessage (86 tokens) {
chatgpt-web-app-1  |   max_tokens: 1000,
chatgpt-web-app-1  |   model: 'gpt-3.5-turbo',
chatgpt-web-app-1  |   temperature: 0.8,
chatgpt-web-app-1  |   top_p: 1,
chatgpt-web-app-1  |   presence_penalty: 1,
chatgpt-web-app-1  |   messages: [
chatgpt-web-app-1  |     {
chatgpt-web-app-1  |       role: 'system',
chatgpt-web-app-1  |       content: 'You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\n' +
chatgpt-web-app-1  |         'Knowledge cutoff: 2021-09-01\n' +
chatgpt-web-app-1  |         'Current date: 2023-03-25'
chatgpt-web-app-1  |     },
chatgpt-web-app-1  |     { role: 'user', content: '继续', name: undefined },
chatgpt-web-app-1  |     { role: 'assistant', content: '请问您需要什么样的帮助或回答？', name: undefined },
chatgpt-web-app-1  |     { role: 'user', content: 'Uni-APP 如何创建demo\n\n', name: undefined }
chatgpt-web-app-1  |   ],
chatgpt-web-app-1  |   stream: true
chatgpt-web-app-1  | }
chatgpt-web-app-1  | TimeoutError: OpenAI timed out waiting for response
chatgpt-web-app-1  |     at <anonymous> (/app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:70:24)
chatgpt-web-app-1  |     at new Promise (<anonymous>)
chatgpt-web-app-1  |     at pTimeout (/app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:48:28)
chatgpt-web-app-1  |     at Object.sendMessage (/app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:319:14)
chatgpt-web-app-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
chatgpt-web-app-1  |     at chatReplyProcess (/app/build/index.js:125:22)
chatgpt-web-app-1  |     at <anonymous> (/app/build/index.js:238:5)
```
版本     image: chenzhaoyu94/chatgpt-web:v2.10.8  和现在最新的都是

**Comment by tanpengsccd** [comment]
docker 使用的API 
```yml
version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web #:v2.10.8 # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ports:
      - 13002:3002
    volumes:
      - ./dist:/app/public
    environment:
      # 二选一
      OPENAI_API_KEY: sk-II 脱毛
      # # 二选一
      # OPENAI_ACCESS_TOKEN: xxx
      # # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      # OPENAI_API_BASE_URL: 
      # # API模型，可选，设置 OPENAI_API_KEY 时可用
      # OPENAI_API_MODEL: xxx
      # # 反向代理，可选
      # API_REVERSE_PROXY: xxx
      # # 访问权限密钥，可选
      AUTH_SECRET_KEY: clashus.com
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 3600
      # # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      # SOCKS_PROXY_HOST: xxx
      # # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      # SOCKS_PROXY_PORT: xxx
      # # HTTPS 代理，可选，支持 http，https，socks5
      # HTTPS_PROXY: http://xxx:7890
      MAX_REQUEST_PER_HOUR: 45
```
